---
- hosts: all
  tasks:
        - name: Install basic packeges
          package: name={{item}} state=installed
          with_items:
                - chromium
                - base-devel
                - yaourt
                - ethtool
                - smartmontools
                - tmux
                - docker
                - docker-compose
                - bash-completion
                - vagrant
                - packer-io
                - python-pip
                - python-virtualenv

        - name: Install packages from yaourt
          shell: yaourt -Suy --noconfirm {{item}}
          with_items:
              - chromium-widevine
          become: true
          become_user: sascha

        - name: Install module with pip
          shell: pip install {{item}}
          with_items:
              - jedi
